package com.two_m.yourbarber.model.enums;

public enum NotificationType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    BARBERSHOP_REQUEST,
    BARBERSHOP_REQUEST_DECIDED,
    SUBSCRIPTION_PAYMENT_PENDING,
    SUBSCRIPTION_PAYMENT_DECIDED,
    JOIN_REQUEST,
    JOIN_REQUEST_DECIDED
}
